#!/usr/bin/env python3
"""Package a verified native-battery disk manifest without /tmp backing dependencies.

The source must already have original powerd and no battery publisher (use
prepare_native_battery_candidate.py to migrate a legacy image). This copies and
flattens that disk; it does not remove guest patches or certify a fresh boot.
"""
import argparse
import json
from pathlib import Path
import shutil
import subprocess
import sys

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / 'tools'))
from checkpoint_common import atomic_json, qcow2_backing_chain, sha256, verify_backing_chain
from warm_boot_probe import boot_command


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--manifest', type=Path, required=True)
    p.add_argument('--out', type=Path, required=True)
    p.add_argument('--dtree-raw', type=Path, required=True)
    p.add_argument('--development-activation', action='store_true')
    a = p.parse_args()
    source = json.loads(a.manifest.read_text())
    verify_backing_chain(source['disk']['backing_chain'])
    if Path(source['disk']['path']).stat().st_mode & 0o222:
        p.error('source disk must be sealed read-only')
    for name, expected in source['qemu_inputs'].items():
        if Path(name).resolve() == Path(source['qemu_argv'][0]).resolve():
            continue  # Replaced by the current built QEMU, pinned below.
        if sha256(Path(name)) != expected['sha256']:
            p.error(f'source boot input changed: {name}')
    # Require a new directory, so a published default can never be overwritten.
    a.out = a.out.resolve()
    a.out.mkdir(parents=True, exist_ok=False)
    qimg = REPO / 'qemu-sptm/build/qemu-img'
    disk = a.out / 'system.qcow2'
    subprocess.run([str(qimg), 'convert', '-f', 'qcow2', '-O', 'qcow2',
                    source['disk']['path'], str(disk)], check=True)
    subprocess.run([str(qimg), 'compare', '-f', 'qcow2', '-F', 'qcow2',
                    source['disk']['path'], str(disk)], check=True)
    finish(source, a.manifest, a.out, a.dtree_raw, a.development_activation)


def finish(source, source_manifest, out, raw, activation):
    """Copy launch inputs and generate current DT; also used after an owned conversion."""
    qimg = REPO / 'qemu-sptm/build/qemu-img'
    argv = boot_command(source['qemu_argv'], out)
    # Strip per-run sockets generated by boot_command; launchers supply their own.
    argv = argv[:argv.index('-monitor')]
    argv[0] = str(out / 'qemu-system-aarch64')
    shutil.copy2(REPO / 'qemu-sptm/build/qemu-system-aarch64', argv[0])
    shutil.copy2(qimg, out / 'qemu-img')
    for key in ('-bootkc', '-tc', '-ramdisk', '-sptm', '-txm'):
        index = argv.index(key) + 1
        dest = out / key[1:]
        shutil.copy2(argv[index], dest)
        argv[index] = str(dest)
    tree = out / 'system.dtree'
    subprocess.run([sys.executable, str(REPO / 'dt_fixup.py'), str(raw), str(tree),
                    '-nvram', str(REPO / 'nvram.bin'), '-enable', 'ans', '-enable', 'smc',
                    '-enable', 'sep', '-enable', 'dcp', '-enable', 'spmi', '-dram', '12G']
                   + (['-development-activation'] if activation else []), check=True)
    argv[argv.index('-dtree') + 1] = str(tree)
    argv[argv.index('-display') + 1] = 'none'
    disk = out / 'system.qcow2'
    argv[argv.index('-drive') + 1] = f'if=none,id=ans,file={disk},format=qcow2'
    env = {k: v for k, v in source['qemu_env'].items()
           if k.startswith('DARWIN_') and k not in
           ('DARWIN_PMU_STATE', 'DARWIN_TOUCH_EVENTS', 'DARWIN_INPUT_STATUS')
           and not k.startswith('DARWIN_SMC_')}
    env['DARWIN_RTC_PV'] = '0'
    paths = [Path(argv[0])] + [Path(argv[argv.index(k) + 1])
            for k in ('-bootkc', '-tc', '-ramdisk', '-sptm', '-txm', '-dtree')]
    disk.chmod(0o444)
    atomic_json(out / 'default.json', dict(format='darwin-vm-warm-disk-v1',
        source_manifest=str(source_manifest), battery_source='emulated-smc',
        source_requirement='original powerd; battery publisher removed before packaging',
        qemu_argv=argv, qemu_env=env,
        qemu_inputs={str(f): dict(sha256=sha256(f), bytes=f.stat().st_size) for f in paths},
        disk=dict(path=str(disk), backing_chain=qcow2_backing_chain(qimg, disk))))


if __name__ == '__main__':
    main()
